// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package catworldpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CatWorldServiceClient is the client API for CatWorldService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatWorldServiceClient interface {
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
}

type catWorldServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatWorldServiceClient(cc grpc.ClientConnInterface) CatWorldServiceClient {
	return &catWorldServiceClient{cc}
}

func (c *catWorldServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, "/catworld.CatWorldService/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatWorldServiceServer is the server API for CatWorldService service.
// All implementations must embed UnimplementedCatWorldServiceServer
// for forward compatibility
type CatWorldServiceServer interface {
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	mustEmbedUnimplementedCatWorldServiceServer()
}

// UnimplementedCatWorldServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCatWorldServiceServer struct {
}

func (UnimplementedCatWorldServiceServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedCatWorldServiceServer) mustEmbedUnimplementedCatWorldServiceServer() {}

// UnsafeCatWorldServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatWorldServiceServer will
// result in compilation errors.
type UnsafeCatWorldServiceServer interface {
	mustEmbedUnimplementedCatWorldServiceServer()
}

func RegisterCatWorldServiceServer(s grpc.ServiceRegistrar, srv CatWorldServiceServer) {
	s.RegisterService(&CatWorldService_ServiceDesc, srv)
}

func _CatWorldService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatWorldServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catworld.CatWorldService/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatWorldServiceServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatWorldService_ServiceDesc is the grpc.ServiceDesc for CatWorldService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatWorldService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catworld.CatWorldService",
	HandlerType: (*CatWorldServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _CatWorldService_Connect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catworldpb/catworld.proto",
}
